config/routes.rb
Rails.application.routes.draw do
  resources :ripples, except: [:edit, :destroy]

end

app/models/ripple.rb
class Ripple < ActiveRecord::Base
  validates :name, :message, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show, :edit, :update, :destroy]

  # GET /ripples
  # GET /ripples.json
  def index
    #@ripples = Ripple.all
    @ripples = Ripple.order("created_at DESC")
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # GET /ripples/1/edit
  def edit
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)

    respond_to do |format|
      if @ripple.save
        format.html { redirect_to ripples_url, notice: 'Ripple was successfully created.' }
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ripples/1
  # PATCH/PUT /ripples/1.json
  def update
    respond_to do |format|
      if @ripple.update(ripple_params)
        format.html { redirect_to ripples_url, notice: 'Ripple was successfully updated.' }
        format.json { render :show, status: :ok, location: @ripple }
      else
        format.html { render :edit }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ripples/1
  # DELETE /ripples/1.json
  def destroy
    @ripple.destroy
    respond_to do |format|
      format.html { redirect_to ripples_url, notice: 'Ripple was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :url, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CONSCIOUS/mess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <h1>CONSCIOUS/mess</h1>
    <h2>...a stream of anonymous online ramblings</h2>
  </div>
<%= yield %>

</body>
</html>

app/views/ripples/_form.html.erb
<%= form_for(@ripple) do |f| %>
  <% if @ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% @ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Your name or alias (required)</strong><br>

    <%= f.text_field :name %>
  </div>
  <div class="field">
    <strong>A website, yours or otherwise (optional)</strong><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <strong>Your message/note/quote/rant (required)</strong><br>
    <%= f.text_area :message, cols: 70, rows: 20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ripples/edit.html.erb
<h1>Editing Ripple</h1>

<%= render 'form' %>

<%= link_to 'Show', @ripple %> |
<%= link_to 'Back', ripples_path %>

app/views/ripples/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <% if !ripple.url.blank? %>
	  <td id="table_text">
	    <%= link_to truncate(strip_tags(ripple.name), length: 20), ripple.url %></td>
	<% else %>
	  <td id="table_text"><%= truncate(strip_tags(ripple.name), length: 20) %></td>
        <% end %>
        <td id="table_text"><%= truncate(strip_tags(ripple.message), length: 60) %></td>
        <td id="table_text"><%= ripple.created_at %></td>
        <td id="table_text"><%= link_to 'Show', ripple %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="links">
  <%= link_to 'Newest', new_ripple_path %>
  <%= link_to 'Previous 10 Ripples', new_ripple_path %>
  <%= link_to 'Next 10 Ripples', new_ripple_path %>
  <%= link_to 'Oldest', new_ripple_path %>
  <%= link_to 'New Ripple', new_ripple_path %>
</div>

app/views/ripples/new.html.erb
<h1>Say What's On Your Mind</h1>

<%= render 'form' %>

<div id="links">
  <%= link_to 'Back', ripples_path %>
</div>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

<div id="postedBy">
  <strong>Posted By:</strong>
  <% if !@ripple.url.blank? %>
     <%= link_to @ripple.name, @ripple.url %>
   <% else %>
     <%= @ripple.name %>
  <% end %>
</div>

<div id="message">
    <%= @ripple.message %>
</div>

<div id="links">
  <%= link_to 'Back', ripples_path %>
</div>